/*-
 * #%L
 * clij2 fft
 * %%
 * Copyright (C) 2020 - 2025 Robert Haase, MPI CBG
 * %%
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 
 * 3. Neither the name of the MPI CBG nor the names of its contributors
 *    may be used to endorse or promote products derived from this software without
 *    specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 * #L%
 */
package net.haesleinhuepf.clijx.plugins;

import org.jocl.NativePointerObject;
import org.scijava.plugin.Plugin;

import net.haesleinhuepf.clij.clearcl.ClearCLBuffer;
import net.haesleinhuepf.clij.coremem.enums.NativeTypeEnum;
import net.haesleinhuepf.clij.macro.CLIJMacroPlugin;
import net.haesleinhuepf.clij.macro.CLIJOpenCLProcessor;
import net.haesleinhuepf.clij.macro.documentation.OffersDocumentation;
import net.haesleinhuepf.clij2.AbstractCLIJ2Plugin;
import net.haesleinhuepf.clij2.CLIJ2;
import net.haesleinhuepf.clij2.utilities.HasAuthor;
import net.haesleinhuepf.clij2.utilities.HasClassifiedInputOutput;
import net.haesleinhuepf.clij2.utilities.IsCategorized;

/**
 * This plugin performs an inverse Fast Fourier Transform (FFT) on a GPU buffer.
 * It is designed to work with FFTs generated by the ForwardFFT plugin.
 * The output is a real-valued image in spatial domain.
 */
@Plugin(type = CLIJMacroPlugin.class, name = "CLIJx_inverseFFT")
public class InverseFFT extends AbstractCLIJ2Plugin implements
		CLIJMacroPlugin, CLIJOpenCLProcessor, OffersDocumentation, HasAuthor, HasClassifiedInputOutput, IsCategorized {

	/**
	 * Executes the inverse FFT operation using the provided arguments.
	 *
	 * @return true if the operation was successful
	 */
	@Override
	public boolean executeCL() {
		boolean result = runInverseFFT(getCLIJ2(), (ClearCLBuffer) (args[0]), (ClearCLBuffer) (args[1]));
		return result;
	}

	/**
	 * Runs the inverse FFT on the input buffer and returns the result in a new buffer.
	 *
	 * @param clij2 the CLij2 instance for GPU operations
	 * @param gpuFFT the input buffer containing the FFT data (complex, packed format)
	 * @param dims the dimensions of the output buffer (real-valued, spatial domain)
	 * @return the output buffer containing the inverse FFT result
	 */
	public static ClearCLBuffer runInverseFFT(CLIJ2 clij2, ClearCLBuffer gpuFFT, long[] dims) {

		// create GPU memory for FFT
		ClearCLBuffer out = clij2.create(dims, NativeTypeEnum.Float);

		runInverseFFT(clij2, gpuFFT, out);
		
		return out;
	}

	
	/**
	 * Runs the inverse FFT on the input buffer and writes the result to the output buffer.
	 *
	 * @param clij2 the CLij2 instance for GPU operations
	 * @param gpuFFT the input buffer containing the FFT data (complex, packed format)
	 * @param gpuImg the output buffer for the inverse FFT result (real-valued, spatial domain)
	 * @return true if the operation was successful
	 */
	public static boolean runInverseFFT(CLIJ2 clij2, ClearCLBuffer gpuFFT, ClearCLBuffer gpuImg) {
	
		// get the long pointers to in, out, context and queue.
		long l_in = ((NativePointerObject) (gpuFFT.getPeerPointer()
			.getPointer())).getNativePointer();
		long l_out = ((NativePointerObject) (gpuImg.getPeerPointer()
			.getPointer())).getNativePointer();
		long l_context = ((NativePointerObject) (clij2.getCLIJ().getClearCLContext()
			.getPeerPointer().getPointer())).getNativePointer();
		long l_queue = ((NativePointerObject) (clij2.getCLIJ().getClearCLContext()
			.getDefaultQueue().getPeerPointer().getPointer())).getNativePointer();

		if (gpuImg.getDimensions().length==2) {
			// call the native code that runs the inverse FFT
			clij2fftWrapper.fft2dinv_32f_lp((long) (gpuImg.getWidth()), gpuImg.getHeight(),
					l_in, l_out, l_context, l_queue);
		}
		
		if (gpuImg.getDimensions().length==3) {
			// call the native code that runs the inverse FFT
			clij2fftWrapper.fft3dinv_32f_lp((long) (gpuImg.getWidth()), gpuImg.getHeight(), gpuImg.getDepth(),
					l_in, l_out, l_context, l_queue);
		}
	
		return true;
	}

	/**
	 * Creates an output buffer with the appropriate dimensions for the inverse FFT result.
	 * <p>
	 * Note: This method assumes the input FFT buffer was generated by ForwardFFT and has even dimensions.
	 * For proper handling, the original size of the input image should be tracked.
	 * </p>
	 *
	 * @param input the input FFT buffer
	 * @return the output buffer for the inverse FFT result
	 */
	@Override
	public ClearCLBuffer createOutputBufferFromSource(ClearCLBuffer input) {
		ClearCLBuffer in = (ClearCLBuffer) args[0];
		
		long[] dimensions=new long[in.getDimensions().length];
		
		// TODO this assumes even input dimension and no extension
		// the assumption is not good most of the time, so we'll have
		// to revisit this.  To do proper inverse need to keep track of 
		// original size
		dimensions[0]=in.getDimensions()[0]-2;
		
		for (int d=1;d<in.getDimensions().length;d++) {
			dimensions[d]=in.getDimensions()[d];
		}
		
		return getCLIJ2().create(dimensions, NativeTypeEnum.Float);
	}

	/**
	 * Provides a description of the plugin's parameters.
	 *
	 * @return a string describing the input and output parameters
	 */
	@Override
	public String getParameterHelpText() {
		return "Image input, ByRef Image destination";
	}

	/**
	 * Provides a description of the plugin's functionality.
	 *
	 * @return a string describing what the plugin does
	 */
	@Override
	public String getDescription() {
		return "Performs inverse FFT (currently only works with FFT generated by Clij ForwardFFT)";
	}

	/**
	 * Specifies the dimensions supported by this plugin.
	 *
	 * @return a string indicating the supported dimensions
	 */
	@Override
	public String getAvailableForDimensions() {
		return "2D, 3D";
	}

	/**
	 * Provides the name of the plugin's author.
	 *
	 * @return the author's name
	 */
	@Override
	public String getAuthorName() {
		return "Brian Northan";
	}

	/**
	 * Specifies the type of input expected by this plugin.
	 *
	 * @return a string describing the input type
	 */
	@Override
	public String getInputType() {
		return "Image";
	}

	/**
	 * Specifies the type of output produced by this plugin.
	 *
	 * @return a string describing the output type
	 */
	@Override
	public String getOutputType() {
		return "Image";
	}

	/**
	 * Specifies the category under which this plugin is classified.
	 *
	 * @return a string describing the plugin's category
	 */
	@Override
	public String getCategories() {
		return "Filter";
	}

}
